name: Check URL Status

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0

env:
  LINK_TRACKING_ISSUE_NUMBER: 1
  
permissions:
  issues: write

jobs:
  check-urls:
    env:
      LYCHEE_REPORT_FILE: ./lychee/out.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose --exclude-path ./node_modules/ "./**/*.js" "./**/*.ts" "./**/*.html" "./**/*.json" "./**/*.md"

      - name: Save Lychee Exit Code
        run: echo "LYCHEE_EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Read Lychee report
        if: always()
        id: readReport
        run: |
          FILE_CONTENT=$(cat ${{ env.LYCHEE_REPORT_FILE }})
          echo "FILE_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$FILE_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - run: echo "${{ env.FILE_CONTENT }}"

      - name: Debug Issue Number
        run: |
          echo "Checking if issue number ${{ env.LINK_TRACKING_ISSUE_NUMBER }} exists"
          gh issue view ${{ env.LINK_TRACKING_ISSUE_NUMBER }} || echo "Issue not found"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update link tracking issue (update invalid links)
        if: env.LYCHEE_EXIT_CODE != 0
        uses: actions-cool/issues-helper@v3
        with:
          actions: "update-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ env.LINK_TRACKING_ISSUE_NUMBER }}
          state: "open"
          body: ${{ env.FILE_CONTENT }}
          update-mode: "replace"

      - name: Update link tracking issue (no invalid links)
        if: env.LYCHEE_EXIT_CODE == 0
        uses: actions-cool/issues-helper@v3
        with:
          actions: "update-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ env.LINK_TRACKING_ISSUE_NUMBER }}
          state: "closed"
          body: "No invalid links found! 🤖"
          update-mode: "replace"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lychee-report
          path: ${{ env.LYCHEE_REPORT_FILE }}